### ISSUE TITLE
Another 1.8 err

### ISSUE THREAD

**Issue by Chopnex** [pqtriick/LabySK#2]
The plugin loads but I receive this error upon loading. I am using skript 2.6.5-for-1.8 on flamepaper 2.0 for 1.8.8

[20:36:29 INFO]: [LabySK] Enabling LabySK v1.2
[20:36:29 WARN]: java.lang.NullPointerException: Cannot invoke "ch.njol.skript.SkriptAddon.loadClasses(String, String[])" because "de.pqtriick.labysk.LabySK.addon" is null
[20:36:29 WARN]:        at de.pqtriick.labysk.LabySK.onEnable(LabySK.java:47)
[20:36:29 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:36:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[20:36:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[20:36:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[20:36:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[20:36:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:404)
[20:36:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:368)
[20:36:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358)
[20:36:29 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:257)
[20:36:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:589)
[20:36:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:135)
[20:36:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[20:36:29 INFO]: [LabySK] LabySK Loaded successfully

**Comment by Chopnex** [comment]
And even though it is loading it does not work. The syntaxes are not registrered somehow :/

**Comment by Chopnex** [comment]
Using LabyApi-2.0.1.jar

**Comment by pqtriick** [comment]
can you add me on discord? elcitron_

**Comment by pqtriick** [comment]
But i don't know what's wrong for me it works in spigot 1.8.8

**Comment by pqtriick** [comment]
So i have initalized the addon instance onLoad and onEnable. Try downloading the jar and execute it
https://github.com/pqtriick/LabySK/releases/tag/mcv_1.8.8

**Comment by Chopnex** [comment]
Still an error and also it says it can't find skript in the folder. https://pastebin.com/tu32xJba

Added you on discord

**Comment by pqtriick** [comment]
Issue fixed.
Download for 1.8: https://github.com/pqtriick/LabySK/releases/tag/mcv_1.8.8
